pp
app/models
app/models/student.rb
app/models/teacher.rb
db
db/ar-students.sqlite3
db/config.rb
db/data
db/data/students.csv
db/data/teachers.csv
db/migrate
db/migrate/20121011144238_create_students.rb
folders.rb
Gemfile
Gemfile.lock
lib
lib/students_importer.rb
Rakefile
README.md
spec
spec/migrate_create_table_spec.rb
spec/migrate_timestamps_spec.rb
spec/student_internationalized_spec.rb
spec/student_spec.rb
students.db